#!/usr/bin/perl
# Copyright (C) 2014 Tony Crisci <tony@dubstepdish.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Requires playerctl binary to be in your path (except cmus)
# See: https://github.com/acrisci/playerctl

# Set instance=NAME in the i3blocks configuration to specify a music player
# (playerctl will attempt to connect to org.mpris.MediaPlayer2.[NAME] on your
# DBus session).

use Env qw(BLOCK_INSTANCE);

my $status = qx(ps -e | grep mpd);
if ($status eq '')
{
    exit(0);
}
else
{
    my @metadata = ();
    my $player_arg = "";

    if ($BLOCK_INSTANCE) {
        $player_arg = "--player='$BLOCK_INSTANCE'";
    }

    if ($ENV{'BLOCK_BUTTON'} == 1) {
        system("mpc toggle");
    } elsif ($ENV{'BLOCK_BUTTON'} == 2) {
        system("mpc prev");
    } elsif ($ENV{'BLOCK_BUTTON'} == 3) {
        system("mpc next");
    } 


    my $artist = qx(mpc current);
# exit status will be nonzero when playerctl cannot find your player
    exit(0) if $?;
    push(@metadata, $artist) if $artist;

    my $title = qx(mpc current);
    exit(0) if $?;
    push(@metadata, $title) if $title;

    print($title) if @metadata;
}


